name: NPM CD

on:
  push:
    branches:
      - master

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 12
      uses: actions/setup-node@master
      with:
        node-version: '12'
    - name: npm install and test
      run: |
        npm install
        npm test

    - name: Publish if version has been updated
      if: success()
      uses: pascalgn/npm-publish-action@51fdb4531e99aac1873764ef7271af448dc42ab4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
